import "../App.css";

export default function UserManual(){
    return(
        <div>
            <div className="mx-5 mb-5">
                <h5 className="text-center"> <strong>User Manual</strong></h5>
                <div> Lorem ipsum dolor sit amet consectetur adipisicing elit. Id a ratione ullam, atque obcaecati rerum architecto maxime provident incidunt eaque ex repellendus explicabo eos repudiandae sequi voluptatum modi. Ratione, animi?
                Expedita, vitae deserunt! Velit aspernatur voluptatibus cupiditate ipsa. Iste cum nisi ullam nostrum quidem, rerum repudiandae praesentium, temporibus repellat molestias consectetur similique corporis hic dolor optio atque unde dolorum ad?
                Perspiciatis cupiditate inventore magnam est explicabo amet velit assumenda, totam nulla hic illum alias modi esse ullam! Sapiente eaque tempore dolore atque obcaecati nostrum aspernatur dicta, similique ad dignissimos vel?
                Non, enim rem blanditiis maiores quibusdam distinctio minima harum tempora ducimus quia ex ipsa, maxime architecto, hic ullam ipsum error culpa veritatis et repellendus! Fugit veniam perferendis aut iste alias!
                Ut porro, expedita voluptatibus ea accusamus perspiciatis ullam enim tempora reprehenderit esse deleniti laboriosam sint sed, repellat quos voluptate? Unde voluptatibus autem architecto distinctio, quae temporibus fuga repudiandae quia tenetur.
                Accusamus eaque labore nisi vero qui quasi commodi dolores praesentium quia mollitia, cumque iusto optio consectetur expedita exercitationem molestiae! Qui quaerat debitis nam ad quo earum aliquam laudantium ipsam quibusdam!
                Nulla libero minima assumenda eos sequi, labore magnam quos, tempore cumque aut unde recusandae, inventore atque corrupti beatae hic error reprehenderit natus eveniet in voluptates quaerat! Reiciendis eum labore doloremque?
                Cupiditate, commodi. In provident veniam expedita? Vero quidem beatae, optio, autem ea similique eligendi commodi, repudiandae consequatur pariatur porro sit! Dolore alias sequi doloribus quis earum officia mollitia illum dolorem!
                Dolorum facere corrupti ab provident placeat quibusdam beatae nisi voluptas praesentium rerum, totam vel vero? Dolorum placeat nesciunt sapiente neque asperiores accusamus deleniti ipsa nobis rem beatae, quo animi ipsum.
                Ad, sequi illo quae aliquam consequatur labore sed dolorem voluptas reiciendis inventore praesentium. Nihil iusto consequuntur possimus, minima perspiciatis a voluptate corrupti ex rem ipsa consequatur amet, delectus quisquam sequi. </div>
            </div>
            <hr />
            <hr />
            <div className="mx-5 mb-5">
                <h5 className="text-center"><strong>Future Plans</strong></h5>
                <div>
                    <div>
                        <span><strong>1. Search by Strength and parameters:</strong>  This is for searching the students only. In this feature one window will be provided to the admin and support which contain: <br /></span>
                        <span className="mx-3 d-block">a.	Search box</span>
                        <span className="mx-3 d-block">b.	Multiselect Strength search box</span>
                        <span className="mx-3 d-block">c.	Multiselect other parameters search box</span>
                        <span className="mx-3 d-block">d.	Filter like</span>
                            <span className="mx-5 d-block">i.	Semester (Multiselect)</span>
                            <span className="mx-5 d-block">ii.	Department (Multiselect)</span>
                        <span className="mx-3 d-block">e.	And a Table which contain:</span>
                            <span className="mx-5 d-block">i.	Name, Department, Semester, reg no of student </span>
                            <span className="mx-5 d-block">ii.	The list of teachers gives him/her such feedbacks</span>
                        <span className="mx-3 d-block">** There will be two types of sorting of table data:</span>
                            <span className="mx-5 d-block">a.    Sort by the number of positive feedbacks where the number of total feedback, semester, teacher is immaterial.</span>
                            <span className="mx-5 d-block">b.    Sort by percentage of positive feedback where number of totals feedbacks, semester and number of teachers all will be considered.</span>
                    </div>
                    <hr />
                    <div>
                        <span><strong>2. Report: </strong>This window will contain the report or suggestion for a teacher or student about his/her next step to be better. This content will be generated by Generative AI after analysing his/her feedbacks. This analysis will be done by default with the last 12 months data of a teacher and all previous data of a student. The feature will be like below. There will be three sections of the report: <br /> </span>
                        <span className="mx-3 d-block">a.	 Areas, which need improvement: Based on feedbacks also with “additional comments” there will be multiple points that on which things the user need to work now to make it better. This result will be generated after analysing all the rating parameters not only “Areas of improvement” parameters. This may farther classify as:</span>
                            <span className="mx-5 d-block">i.	Very weak areas</span>
                            <span className="mx-5 d-block">ii.	Weak areas </span>
                        <span className="mx-3 d-block">b.	Strong areas: Based on feedbacks also with “additional comments” there will be multiple points that are good enough of the user and must be maintain like this. This may include a feature: Points the strengths which became better from the previous feedbacks. This will be done by a comparisons analysis of old and new feedbacks.</span>
                        <span className="mx-3 d-block">c.	Conclusion: The final conclusion in 2 to 3 lines about his growth and future steps he/she should take. </span>
                    </div>
                </div>
            </div>
            <hr /> 
            <div className="text-center m-3">
                <div>Please feel free to reach us if you have any opinions or features we should include in the application to make it more usefull for you.</div>
                <div>Mail us on support@eduinsights.in</div>
                <div>&copy; Copyright 2024 by eduinsights.in || All Rights Reserved</div>
            </div>
        </div>
    )
}